// MFCActiveXControl1.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (MFCActiveXControl1.tlb) that will become a resource in
// MFCActiveXControl1.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(b45083f7-f41d-40c0-886d-ac138bc35eab), version(1.0),
  control ]
library MFCActiveXControl1Lib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CMFCActiveXControl1Ctrl
	[ 
		uuid(27364db4-876a-40cd-a243-537814bc6341)
	]
	dispinterface _DMFCActiveXControl1
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  Event dispatch interface for CMFCActiveXControl1Ctrl

	[ 
		uuid(ef6b1b5c-78f1-4459-b47e-29acbd7ffb95)
	]
	dispinterface _DMFCActiveXControl1Events
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CMFCActiveXControl1Ctrl
	[
		uuid(1fb2728a-8948-4058-8172-15065a9ab95b)
	]
	coclass MFCActiveXControl1
	{
		[default] dispinterface _DMFCActiveXControl1;
		[default, source] dispinterface _DMFCActiveXControl1Events;
	};

};
